import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import Image from "next/image";
import styles from "../../../../styles/Home.module.css";

import { postData } from "../../../../types/communityType";
import PostDetail from "../../../../components/PostDetail";

const emptyPost: postData = {
  categoryPk: -1,
  categoryName: "",
  pk: -1,
  title: " ",
  content: " ",
  viewCount: -1,
  likeCount: -1,
  commentCount: -1,
  imageUrl: null,
  writtenAt: " ",
  writerNickName: " ",
  writerProfileUrl: null,
};

const Home: NextPage = () => {
  const router = useRouter();
  const { post_pk } = router.query;

  const [post, setPost] = useState<postData>(emptyPost);

  // fetch to get post list async function
  const getPosts = async () => {
    const response = await fetch(`/api/community/posts/${post_pk}`);
    const data = await response.json();
    console.log(data);
    setPost(data);
    // setFilteredPosts(postList);
  };

  useEffect(() => {
    if (!!post_pk && post.pk === -1) {
      (async () => {
        await Promise.all([getPosts()]);
      })();
    }
  }, [post_pk]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!!post && post.pk !== -1 ? (
          <>
            {console.log("post", post)}
            <PostDetail data={post} />
          </>
        ) : (
          <div>없는 포스트입니다.</div>
        )}
        <h1 className="text-3xl font-bold underline">{post_pk}</h1>
      </main>
    </div>
  );
};

export default Home;
